# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='login_app.User'),
        ),
    ]
